FROM python:3.7-slim

COPY requirements.txt /requirements.txt

RUN pip install -r requirements.txt

COPY /run_producer.py  run_producer.py
COPY /common /common
COPY /producer /producer

ENTRYPOINT ["python", "run_producer.py"]