FROM python:3.7-slim

COPY requirements.txt /requirements.txt

RUN pip install -r requirements.txt

COPY /run_consumer.py  run_consumer.py
COPY /common /common
COPY /consumer /consumer

ENTRYPOINT ["python", "run_consumer.py"]