# Generated by Django 2.1.7 on 2019-03-19 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sftp_host',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sftp_path',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='sftp_port',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
